contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #playground channel"
    url: https://nfcore.slack.com/channels/playground
    about: Discussion about the nf-core/playground pipeline
